# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: citizen_code_scripts 1.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "citizen_code_scripts"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Glenn Jahnke", "Erik Hanson", "Bion Johnson", "David Balatero"]
  s.date = "2016-11-10"
  s.description = "Citizen Code tools for easy building, testing, and deploying RoR/Android/iOS apps into teh cloudz"
  s.email = "accounts+rubygems@citizencode.io"
  s.executables = ["citizen"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/citizen",
    "citizen.yml",
    "citizen_code_scripts.gemspec",
    "lib/citizen_code_scripts.rb",
    "lib/citizen_code_scripts/base.rb",
    "lib/citizen_code_scripts/begin.rb",
    "lib/citizen_code_scripts/colorize.rb",
    "lib/citizen_code_scripts/doctor.rb",
    "lib/citizen_code_scripts/help.rb",
    "lib/citizen_code_scripts/heroku_doctor.rb",
    "lib/citizen_code_scripts/kill_db_sessions.rb",
    "lib/citizen_code_scripts/levenstein.rb",
    "lib/citizen_code_scripts/pushit.rb",
    "lib/citizen_code_scripts/rspec.rb",
    "lib/citizen_code_scripts/test.rb",
    "lib/citizen_code_scripts/todayi.rb",
    "lib/citizen_code_scripts/update.rb",
    "spec/passing_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/citizencode/citizen_code_scripts"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "Citizen Code command-line scripts for easy testing and deployment"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2"])
      s.add_development_dependency(%q<pry>, [">= 0"])
      s.add_development_dependency(%q<pry-stack_explorer>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2"])
      s.add_dependency(%q<pry>, [">= 0"])
      s.add_dependency(%q<pry-stack_explorer>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2"])
    s.add_dependency(%q<pry>, [">= 0"])
    s.add_dependency(%q<pry-stack_explorer>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

