# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: citizen-scripts 1.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "citizen-scripts".freeze
  s.version = "1.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Harlan T Wood".freeze, "Glenn Jahnke".freeze, "Erik Hanson".freeze, "Bion Johnson".freeze, "David Balatero".freeze]
  s.date = "2017-09-20"
  s.description = "Tools for easy building, testing, and deploying RoR apps".freeze
  s.email = "dev@comakery.com".freeze
  s.executables = ["citizen".freeze]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".pairs",
    ".rspec",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/citizen",
    "citizen-scripts.gemspec",
    "citizen.yml",
    "lib/citizen_scripts.rb",
    "lib/citizen_scripts/base.rb",
    "lib/citizen_scripts/begin.rb",
    "lib/citizen_scripts/colorize.rb",
    "lib/citizen_scripts/deploy.rb",
    "lib/citizen_scripts/diff.rb",
    "lib/citizen_scripts/doctor.rb",
    "lib/citizen_scripts/help.rb",
    "lib/citizen_scripts/heroku_doctor.rb",
    "lib/citizen_scripts/kill_db_sessions.rb",
    "lib/citizen_scripts/levenstein.rb",
    "lib/citizen_scripts/promote.rb",
    "lib/citizen_scripts/pushit.rb",
    "lib/citizen_scripts/rspec.rb",
    "lib/citizen_scripts/test.rb",
    "lib/citizen_scripts/todayi.rb",
    "lib/citizen_scripts/update.rb"
  ]
  s.homepage = "http://github.com/CoMakery/citizen-scripts".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.11".freeze
  s.summary = "Command-line scripts for easy testing and deployment".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2"])
      s.add_development_dependency(%q<pry>.freeze, [">= 0"])
      s.add_development_dependency(%q<pry-stack_explorer>.freeze, [">= 0"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    else
      s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2"])
      s.add_dependency(%q<pry>.freeze, [">= 0"])
      s.add_dependency(%q<pry-stack_explorer>.freeze, [">= 0"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    end
  else
    s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2"])
    s.add_dependency(%q<pry>.freeze, [">= 0"])
    s.add_dependency(%q<pry-stack_explorer>.freeze, [">= 0"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
  end
end

